# Provisionnement - Assurance Non Vie

L'objectif de ce projet est d'appliquer différentes méthodes de provisionnement à un jeu de données acturiels issu du site [casact.org](https://www.casact.org/publications-research/research/research-resources/loss-reserving-data-pulled-naic-schedule-p).

# Sommaire

* [Packages](#partie1)
* [Import des données](#partie2)
* [Mise en forme des données: Triangle de liquidation](#partie3)
* [Méthode de référence: Approche Chain Ladder](#partie4)
    * [Estimation déterministe de la provision](#partie41)
    * [Intervalle de confiance: Méthode de Mack](#partie42)
    * [Distribution de la provision: Boostrap](#partie43)
* [Vérification des hypothèses](#partie5)
* [Backtesting: RMSE - MAE - MAPE](#partie6)

## Packages <a id="partie1"></a>

In [1]:
# %pip install chainladder

import locale
import pandas as pd
import numpy as np
import chainladder as cl
import matplotlib.pyplot as plt

%matplotlib inline

## Import des données <a id="partie2"></a>

In [2]:
df = pd.read_csv("wkcomp_pos_98-07.csv")
df

,GRCODE,GRNAME,AccidentYear,DevelopmentYear,DevelopmentLag,IncurredLosses,CumPaidLoss,BulkLoss,EarnedPremDIR,EarnedPremCeded,EarnedPremNet,Single,PostedReserves2007
0,86,Allstate Ins Co Grp,1998,1998,1,10079,1201,1518,7133,-860,7993,0,135699.214
1,86,Allstate Ins Co Grp,1998,1999,2,9643,2652,240,7133,-860,7993,0,135699.214
2,86,Allstate Ins Co Grp,1998,2000,3,3207,3172,13,7133,-860,7993,0,135699.214
3,86,Allstate Ins Co Grp,1998,2001,4,3202,3178,8,7133,-860,7993,0,135699.214
4,86,Allstate Ins Co Grp,1998,2002,5,3197,3180,8,7133,-860,7993,0,135699.214
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12095,44300,Tower Ins Co Of NY,2005,2010,6,2919,2834,-205,10758,2820,7939,1,18540.838
12096,44300,Tower Ins Co Of NY,2005,2011,7,2809,2899,-318,10758,2820,7939,1,18540.838
12097,44300,Tower Ins Co Of NY,2005,2012,8,3001,2963,-240,10758,2820,7939,1,18540.838
12098,44300,Tower Ins Co Of NY,2005,2013,9,3207,2992,19,10758,2820,7939,1,18540.838
12099,44300,Tower Ins Co Of NY,2005,2014,10,3216,3216,0,10758,2820,7939,1,18540.838

## Mise en forme des données: Triangle de liquidation <a id="partie3"></a>

In [3]:
# Certaines méthodes du package chainladder ne fonctionnent qu'avec une horloge 
# anglophone sur la machine. On regle donc ce probleme manuellement dans le notebook. 

locale.setlocale(locale.LC_TIME, 'English_United States.1252')
print(locale.getlocale(locale.LC_TIME))

('English_United States', '1252')

In [4]:
# Chargement des sinsitres survenus (IncurredLosses) avec Chainladder

bulk_data = cl.Triangle(
    df,
    origin="AccidentYear",
    development="DevelopmentYear",
    columns="IncurredLosses",
    index=["GRNAME"]
)
bulk_data

c:\Users\Onel\AppData\Local\Programs\Python\Python314\Lib\site-packages\chainladder\core\triangle.py:548: UserWarning:
                The cumulative property of your triangle is not set. This may result in
                undesirable behavior. In a future release this will result in an error.

  warnings.warn(

            Triangle Summary
Valuation:           2016-12
Grain:                  OYDY
Shape:      (132, 1, 19, 19)
Index:              [GRNAME]
Columns:    [IncurredLosses]

In [5]:
# Sommes des montants sur l'index "GRNAME" et passage à des valeurs cumulatives

data = bulk_data.sum().loc[:, :, "1998":"2007", :120].incr_to_cum().dropna()
data

            12         24         36          48          60          72          84          96          108         120
1998  1474384.0  2956897.0  4407489.0   5834174.0   7250711.0   8666008.0  10094283.0  11531774.0  12983881.0  14438098.0
1999  1544524.0  3081128.0  4632230.0   6197068.0   7773405.0   9379374.0  11028768.0  12683132.0  14385367.0  16088915.0
2000  1623212.0  3319103.0  5037891.0   6775389.0   8535552.0  10316198.0  12115135.0  13920190.0  15735471.0  17552132.0
2001  1821092.0  3648373.0  5511198.0   7388004.0   9278363.0  11181447.0  13123219.0  15072576.0  17037394.0  19014458.0
2002  1970128.0  4015975.0  6060973.0   8108033.0  10153985.0  12186107.0  14218726.0  16250405.0  18281436.0  20306770.0
2003  2361158.0  4661459.0  6907721.0   9125479.0  11302482.0  13481827.0  15610153.0  17732002.0  19852667.0  21980285.0
2004  2693419.0  5229679.0  7661394.0  10005005.0  12301674.0  14578511.0  16838091.0  19086405.0  21338986.0  23591838.0
2005  2843577.0  5469101.0  7967425.0  10408980.0  12803562.0  15171279.0  17531805.0  19891700.0  22264625.0  24610018.0
2006  2810373.0  5528934.0  8146451.0  10698887.0  13205810.0  15693292.0  18166404.0  20648326.0  23106153.0  25537981.0
2007  2389599.0  4754680.0  7065131.0   9319718.0  11546546.0  13762231.0  15974789.0  18172772.0  20365959.0  22551770.0

In [6]:
# Séparation du triangle supérieur (données d'entrainement)
# Le triangle inférieur servira de données de test pour les méthodes appliquées

triangle_sup = data[data.valuation <= pd.to_datetime('2008-12-31')]
triangle_sup

            12         24         36          48          60          72          84          96          108         120
1998  1474384.0  2956897.0  4407489.0   5834174.0   7250711.0   8666008.0  10094283.0  11531774.0  12983881.0  14438098.0
1999  1544524.0  3081128.0  4632230.0   6197068.0   7773405.0   9379374.0  11028768.0  12683132.0  14385367.0         NaN
2000  1623212.0  3319103.0  5037891.0   6775389.0   8535552.0  10316198.0  12115135.0  13920190.0         NaN         NaN
2001  1821092.0  3648373.0  5511198.0   7388004.0   9278363.0  11181447.0  13123219.0         NaN         NaN         NaN
2002  1970128.0  4015975.0  6060973.0   8108033.0  10153985.0  12186107.0         NaN         NaN         NaN         NaN
2003  2361158.0  4661459.0  6907721.0   9125479.0  11302482.0         NaN         NaN         NaN         NaN         NaN
2004  2693419.0  5229679.0  7661394.0  10005005.0         NaN         NaN         NaN         NaN         NaN         NaN
2005  2843577.0  5469101.0  7967425.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN
2006  2810373.0  5528934.0        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN
2007  2389599.0        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN

In [7]:
triangle_sup.link_ratio.heatmap()